global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nats_exporter"
    static_configs:
      - targets: ["nats_exporter:7777"]
  - job_name: "test_consumer_metrics"
    static_configs:
      - targets: ["testconsumer:8080/actuator/prometheus"]
